# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('likes', models.BigIntegerField(default=0)),
                ('comment', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
