# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openpickr', '0003_auto_20170812_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_like',
        ),
    ]
